### ISSUE TITLE
Can you enable the discussions on this repository?

### ISSUE THREAD

**Issue by Peter-developer01** [wchistow/pystackapi#1]
Like here: https://github.com/wchistow/wchistow/discussions/1

**Comment by wchistow** [comment]
For what?

**Comment by ivan-developer-01** [comment]
For discussions.

**Comment by wchistow** [comment]
Okay, I'll create it. But keep in mind that I'm not developing this project now, and in the future, maybe, I'll redo it.

**Comment by wchistow** [comment]
Here it is: https://github.com/wchistow/pystackapi/discussions/2
