### ISSUE TITLE
The logo is unreadable in dark mode

### ISSUE THREAD

**Issue by Peter-developer01** [wchistow/pystackapi#27]
I'm using an dark mode for GitHub and when I visit the home page ( https://github.com/wchistow/pystackapi ) I see unreadable text at the logo:

![unreadable text in background](https://github.com/wchistow/pystackapi/assets/101456132/254dcee0-70a1-4b9a-bf5e-6b20a52f3fbd)

I know how to fix that, but please provide me with an white text logo version.

**Comment by wchistow** [comment]
What color should be the background of the logo?

**Comment by Peter-developer01** [comment]
> What color should be the background of the logo?

It's enough to leave it transparent.

**Comment by wchistow** [comment]
Something like this (white text is invisible)?
![pystackapi_logo_dark](https://github.com/wchistow/pystackapi/assets/95485831/b438136b-d2e8-492a-a110-969347a1e673)

**Comment by Peter-developer01** [comment]
Great. Now see the magic - https://github.com/wchistow/pystackapi/commit/d6696e0c52879d0b49a7bf87b83c3ddea165768b
