### ISSUE TITLE
Add an example of usage to README.

### ISSUE THREAD

**Issue by nchistov** [wchistow/pystackapi#4]
In README there is no example of usage, please add simple example.

**Comment by Peter-developer01** [comment]
Some examples can be found in [/examples/](https://github.com/wchistow/pystackapi/tree/master/examples).

**Comment by nchistov** [comment]
Ok, there is only one example and it will be good if it added to README.

**Comment by wchistow** [comment]
OK, I'll add this task to ToDo.

**Comment by Peter-developer01** [comment]
@nchistov Yeah, add more examples, and then update README.

**Comment by wchistow** [comment]
I've added an example to README: https://github.com/wchistow/pystackapi/commit/df179207927180253b9ce8dedb795d634d54d865. Can I close this issue?

**Comment by nchistov** [comment]
Yes. I close it.
